name: joy-pharma
recipe: symfony
config:
  webroot: public
  php: 8.3
  via: nginx  # Keep nginx for simplicity, but could be customized to FrankenPHP
  xdebug: false
  database: postgres:16  # Updated to match compose.yaml (was 14, should be 16)
services:
  appserver:
    overrides:
      environment:
        # Xdebug
        XDEBUG_MODE: debug,develop
        PHP_IDE_CONFIG: serverName=appserver
        XDEBUG_CONFIG: discover_client_host=0 client_host=host.docker.internal
        XDEBUG_SESSION_START: lando
        # App
        APP_ENV: dev
        DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres?serverVersion=16&charset=utf8
        # Elasticsearch
        ELASTICSEARCH_HOST: http://elasticsearch:9200
        ELASTICSEARCH_INDEX_PREFIX: joy_pharma
    build_as_root:
      - apt update
      - >-
        curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh'
        | bash
      - apt install -y symfony-cli
      # Install PHP extensions for FrankenPHP compatibility
      - docker-php-ext-enable pdo_pgsql opcache intl zip
    build:
      - composer install --optimize-autoloader --no-scripts
  pgadmin:
    type: compose
    app_mount: false
    ssl: false
    overrides:
      image: dpage/pgadmin4:latest
      command: /entrypoint.sh
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: joy-pharma@mailinator.com
        PGADMIN_DEFAULT_PASSWORD: joy-pharma
        PGADMIN_CONFIG_SERVER_MODE: 'False'
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
        PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
        PGADMIN_LISTEN_PORT: 80
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      ports:
        - ":80"
      healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/misc/ping || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 40s
  database:
    portforward: 5433
  elasticsearch:
    type: elasticsearch
    version: 8.11.0
    portforward: 9200
    config:
      server:
        xpack.security.enabled: false
        xpack.security.enrollment.enabled: false
        discovery.type: single-node
        bootstrap.memory_lock: false
        "action.auto_create_index": true
      jvm.options:
        - "-Xms512m"
        - "-Xmx512m"
        - "-XX:+UseG1GC"
        - "-XX:G1HeapRegionSize=16m"
        - "-XX:+AlwaysPreTouch"
        - "-XX:+UseStringDeduplication"
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
proxy:
  appserver_nginx:
    - joy-pharma.loc
  mailhog:
    - mail.joy-pharma.loc
  pgadmin:
    - pgadmin.joy-pharma.loc  # Fixed typo: was pgladmin
tooling:
  # Add custom console command
  console:
    service: appserver
    cmd: php bin/console
  # Post-start script to run after services are up
  post-start:
    service: appserver
    cmd: composer run-script auto-scripts
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - >-
        docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) >
        /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - >-
        rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2
        $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
excludes:
  - vendor
  - assets/vendor
