# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/var/
      - /app/vendor/
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> elasticsearch ###
  elasticsearch:
    ports:
      - target: 9200
        published: ${ELASTICSEARCH_PORT:-9200}
        protocol: tcp
###< elasticsearch ###

