# Configuration de développement (chargée automatiquement)
# Ce fichier est utilisé par défaut avec docker compose up

services:
  php:
    build:
      target: frankenphp_dev
    image: ${IMAGES_PREFIX:-}joy-pharma-back:dev
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${HTTP3_PORT:-443}/udp:443/udp"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    volumes:
      # Montage du code source pour le hot-reload
      - ./:/app:rw,cached
      - php_data:/app/var
      - php_images:/app/public/images
    # Command pour le développement (sans worker)
    command: ["frankenphp", "serve", "--config", "/etc/caddy/Caddyfile"]

  database:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password}

  elasticsearch:
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

