---
# Production environment override
services:
  php:
    image: ${DOCKERHUB_USERNAME:-joyleonce}/joy-pharma-back:${TAG:-preprod}
    restart: unless-stopped
    container_name: joy-pharma-back-php
    volumes:
      # Monter le fichier .env dans le conteneur
      - ./.env:/app/.env:ro
    environment:
      APP_SECRET: ${APP_SECRET}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      DATABASE_URL: ${DATABASE_URL}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      # Infisical configuration
      INFISICAL_TOKEN: ${INFISICAL_TOKEN:-}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID:-}
    # Port mappings - Traefik is already configured on the server
    ports: []
    networks:
      - traefik_network
      - database_network

networks:
  traefik_network:
    external: true
  database_network:
    external: true
