---
# Production environment override
services:
  php:
    image: ${DOCKERHUB_USERNAME:-joyleonce}/joy-pharma-back:${TAG:-preprod}
    restart: unless-stopped
    container_name: joy-pharma-back-php
    volumes:
      # Monter le fichier .env dans le conteneur
      - ./.env:/app/.env:ro
      # 📁 VOLUMES - Images et uploads persistants
      # En production: utilise ./data/ (dossier du projet, ignoré par Git)
      # En local: utilise ./public/ (via compose.override.yaml)
      - ./data/images:/app/public/images:rw
      - ./data/icons:/app/public/icons:rw
      - ./data/media:/app/public/media:rw
      - ./data/uploads:/app/public/uploads:rw
    environment:
      # Utiliser :80 pour forcer HTTP dans Caddy (Traefik gère déjà le TLS)
      # Le nom de domaine réel est utilisé par Traefik via les labels
      SERVER_NAME: :80
      APP_SECRET: ${APP_SECRET}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      DATABASE_URL: ${DATABASE_URL}
      # Infisical configuration
      INFISICAL_TOKEN: ${INFISICAL_TOKEN:-}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID:-}
      # Configuration mémoire pour FrankenPHP
      GOMEMLIMIT: 12000000000
      PHP_MEMORY_LIMIT: 512M
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 2G
    # Port mappings - Traefik is already configured on the server
    ports: []
    networks:
      - traefik_network
      - database_network

networks:
  traefik_network:
    external: true
  database_network:
    external: true
