App\Entity\Product:
    operations:
        # Admin: List all products
        admin_get_products:
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/admin/products'
            security: 'is_granted("ROLE_ADMIN")'
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'category:read', 'brand:read', 'manufacturer:read']
            openapi:
                summary: 'List all products (Admin)'
                description: 'Get paginated list of all products with filtering and search capabilities'

        # Admin: Get single product
        admin_get_product:
            class: ApiPlatform\Metadata\Get
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'category:read', 'brand:read', 'manufacturer:read']
            openapi:
                summary: 'Get product by ID (Admin)'
                description: 'Get detailed information about a specific product'

        # Admin: Create product
        admin_create_product:
            class: ApiPlatform\Metadata\Post
            uriTemplate: '/admin/products'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\ProductInput
            processor: App\State\Admin\ProductProcessor
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read']
            openapi:
                summary: 'Create new product (Admin)'
                description: 'Create a new product with all its properties and relations'

        # Admin: Update product
        admin_update_product:
            class: ApiPlatform\Metadata\Put
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\ProductInput
            processor: App\State\Admin\ProductProcessor
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read']
            openapi:
                summary: 'Update product (Admin)'
                description: 'Update product information including categories, prices, and stock'

        # Admin: Delete product
        admin_delete_product:
            class: ApiPlatform\Metadata\Delete
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            openapi:
                summary: 'Delete product (Admin)'
                description: 'Permanently delete a product'

        # Admin: Batch delete products
        admin_batch_delete_products:
            class: ApiPlatform\Metadata\Post
            uriTemplate: '/admin/products/batch-delete'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\BatchDeleteInput
            processor: App\State\Admin\BatchDeleteProcessor
            openapi:
                summary: 'Batch delete products (Admin)'
                description: 'Delete multiple products at once'

