App\Entity\Product:
    operations:
        get_product:
            method: 'GET'
            class: ApiPlatform\Metadata\Get
            uriTemplate: '/product/{id}'
            normalizationContext:
                groups: ['id:read','product:read','image:read','media_object:read','unit:read','form:read']
            openapi:
                summary: 'Get a product'
                description: 'Get a product by id'
                parameters:
                    - name: 'id'
                      in: 'path'
                      description:  'The id of the product'

        get_products:
            method: 'GET'
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/products'
            provider: 'App\State\Product\ProductsProvider'
            normalizationContext:
                groups:  ['id:read','product:read','image:read','media_object:read','unit:read','form:read']
            format: 'json'
            openapi:
                summary: 'Get all products'
                description: 'Get all products with pagination and category filter'
                parameters:
                    - name: 'category'
                      in: 'query'
                      description: 'Filter by category ID'
                      required: false
                      schema:
                          type: integer
                    - name: 'page'
                      in: 'query'
                      description: 'Page number'
                      required: false
                      schema:
                          type: integer
                          default: 1
                    - name: 'itemsPerPage'
                      in: 'query'
                      description: 'Items per page'
                      required: false
                      schema:
                          type: integer
                          default: 20
                          maximum: 50
                    - name: 'perPage'
                      in: 'query'
                      description: 'Items per page (alternative to itemsPerPage)'
                      required: false
                      schema:
                          type: integer
                          default: 20
                          maximum: 50
                
        get_products_suggestion:
            method: 'GET'
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/products/suggestion'
            provider: 'App\State\Product\SuggestionProductsProvider'
            normalizationContext:
                groups:  ['id:read','category:read','product:read','image:read','media_object:read','unit:read','form:read']
            openapi:
                summary: 'Get all products home'
                description: 'Get all products home'

        search_products:
            method: 'GET'
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/products/search'
            provider: 'App\State\Product\ProductElasticsearchProvider'
            normalizationContext:
                groups: ['id:read','product:read','image:read','media_object:read','unit:read','form:read']
            openapi:
                summary: 'Search products using Elasticsearch'
                description: 'Search products with full-text search, filters, and pagination'
                parameters:
                    - name: 'q'
                      in: 'query'
                      description: 'Search query'
                      required: false
                      schema:
                          type: string
                    - name: 'query'
                      in: 'query'
                      description: 'Search query (alternative to q)'
                      required: false
                      schema:
                          type: string
                    - name: 'category'
                      in: 'query'
                      description: 'Filter by category ID'
                      required: false
                      schema:
                          type: integer
                    - name: 'brand'
                      in: 'query'
                      description: 'Filter by brand ID'
                      required: false
                      schema:
                          type: integer
                    - name: 'manufacturer'
                      in: 'query'
                      description: 'Filter by manufacturer ID'
                      required: false
                      schema:
                          type: integer
                    - name: 'isActive'
                      in: 'query'
                      description: 'Filter by active status'
                      required: false
                      schema:
                          type: boolean
                    - name: 'page'
                      in: 'query'
                      description: 'Page number'
                      required: false
                      schema:
                          type: integer
                          default: 1
                    - name: 'perPage'
                      in: 'query'
                      description: 'Items per page'
                      required: false
                      schema:
                          type: integer
                          default: 10

        # Admin specific endpoints
        admin_get_products:
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/admin/products'
            security: 'is_granted("ROLE_ADMIN")'
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'category:read', 'brand:read', 'manufacturer:read', 'unit:read', 'form:read']
            openapi:
                summary: 'List all products (Admin)'
                description: 'Get paginated list of all products with filtering and search capabilities'

        admin_get_product:
            class: ApiPlatform\Metadata\Get
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'category:read', 'brand:read', 'manufacturer:read', 'unit:read', 'form:read']
            openapi:
                summary: 'Get product by ID (Admin)'
                description: 'Get detailed information about a specific product'

        admin_create_product:
            class: ApiPlatform\Metadata\Post
            uriTemplate: '/admin/products'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\ProductInput
            processor: App\State\Admin\ProductProcessor
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'unit:read', 'form:read']
            openapi:
                summary: 'Create new product (Admin)'
                description: 'Create a new product with all its properties, relations and images. Upload images first using POST /api/media_objects, then reference them using IRI array (e.g., ["/api/media_objects/123", "/api/media_objects/124"]).'

        admin_update_product:
            class: ApiPlatform\Metadata\Put
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\ProductInput
            processor: App\State\Admin\ProductProcessor
            normalizationContext:
                groups: ['id:read', 'product:read', 'image:read', 'media_object:read', 'unit:read', 'form:read']
            openapi:
                summary: 'Update product (Admin)'
                description: 'Update product information including categories, prices, stock and images. Upload images first using POST /api/media_objects, then reference them using IRI array. Old images not in the array will be automatically deleted.'

        admin_delete_product:
            class: ApiPlatform\Metadata\Delete
            uriTemplate: '/admin/products/{id}'
            security: 'is_granted("ROLE_ADMIN")'
            openapi:
                summary: 'Delete product (Admin)'
                description: 'Permanently delete a product'

        admin_batch_delete_products:
            class: ApiPlatform\Metadata\Post
            uriTemplate: '/admin/products/batch-delete'
            security: 'is_granted("ROLE_ADMIN")'
            input: App\Dto\Admin\BatchDeleteInput
            processor: App\State\Admin\BatchDeleteProcessor
            openapi:
                summary: 'Batch delete products (Admin)'
                description: 'Delete multiple products at once'
        

    normalizationContext:
        groups: ['id:read','product:read','media_object:read','image:read','brand:read','manufacturer:read','category:read','unit:read','form:read']
                      
