App\Entity\Product:
    operations:
        add_products:
            method: "POST"
            class: ApiPlatform\Metadata\Post
            controller: 'App\Controller\Api\Product\AddProductController'
            uriTemplate: "/products"
            deserialize: false
            openapi:
                summary: "Add products"
                description: "Add products"
                
        get_product:
            method: 'GET'
            class: ApiPlatform\Metadata\Get
            uriTemplate: '/product/{id}'
            normalizationContext:
                groups: ['id:read','product:read','image:read']
            openapi:
                summary: 'Get a product'
                description: 'Get a product by id'
                parameters:
                    - name: 'id'
                      in: 'path'
                      description:  'The id of the product'

        get_products:
            method: 'GET'
            class: ApiPlatform\Metadata\GetCollection
            uriTemplate: '/products'
            normalizationContext:
                groups:  ['id:read','product:read','image:read']
            openapi:
                summary: 'Get all products'
                description: 'Get all products'
                
        get_products_summary:
            method: 'GET'
            class: ApiPlatform\Metadata\GetCollection
            controller: 'App\Controller\Api\Product\ProductSummaryController'
            uriTemplate: '/products/home'
            openapi:
                summary: 'Get all products home'
                description: 'Get all products home'

    normalizationContext:
        groups: ['id:read','product:read']
                      
